### ISSUE TITLE
Migrate Travis-CI to GitLab-CI

### ISSUE THREAD

**Issue by temparus** [amiv-eth/amivapi#179]
In order to migrate this project to GitLab, the configuration file for Travis-CI needs to be migrated to GitLab-CI.

**Comment by Leonidaz0r** [comment]
What's wrong with leaving this project on Github? The code is no secret and if some other organisation wants to reuse code, that's perfectly fine.

**Comment by NotSpecial** [comment]
As long as the project and source code stay public, I have no problem with gitlab.

But I agree with @Leonidaz0r -- on github, the code is easier to find.

**Comment by hermannsblum** [comment]
@temparus Is there any argument for moving to GitLab?
I do not really see any.

**Comment by temparus** [comment]
On GitLab, the project would still be public.
The idea was that we can host all of our project in one place. The main argument for the migration to GitLab was that all repositories can be hosted in one place. If we have two hosting services for git repositories, it gets complicated.

**Comment by NotSpecial** [comment]
As of now, we still haven't reached consensus whether a move to the ETH gitlab is the right choice.

Nevertheless, should we decide to do so, setting up the automated tests would be the least of our problems.

We already have a very similar project that uses the same test setup. We could basically copy the
[gitlab CI config](https://gitlab.ethz.ch/amiv/pvk-tool/blob/master/.gitlab-ci.yml).

Basically, this is all we need to run tox in the gitlab CI:

```
backend_tests:
  stage: test
  image: python:alpine
  services:
    - name: bitnami/mongodb:latest
      alias: mongo

  variables:
    MONGO_HOST: mongo
    MONGODB_DATABASE: test_amivapi
    MONGODB_USERNAME: test_user
    MONGODB_PASSWORD: test_pw

  before_script:
    - pip install tox
  script:
    - tox
```
